---
# tasks file for ansible-tmux
- name: Copy main tmux config
  copy:
    src: tmux.conf
    dest: /home/{{user}}/.tmux.conf

- name: Copy colors
  copy:
    src: colors.tmuxtheme
    dest: /home/{{user}}/.colors.tmuxtheme


